import type { Metadata } from 'next'
import { Inter } from 'next/font/google'



import Script from "next/script";
import './globals.css'
import { QueryProvader } from '@/components/QueryProvader';
import Header from '@/components/header';
import Footer from '@/components/footer';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      className='scroll-smooth antialiased'
      suppressHydrationWarning
    >
      
      <body className={`flex min-h-screen flex-col ${inter.className}`}>

      <QueryProvader> 
      <Header />
          <main className='grow'>
       
       
        {children}
    
            
            </main>
      
            </QueryProvader>
      </body>
    </html>
  )
}
